services:
  node:
    image: node:20-alpine
    container_name: apm-node
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./node-src:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - apm-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"