services:
  web:
    build:
      context: ./config/php-apache
      args:
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
      dockerfile: Dockerfile
    container_name: apm-web
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ./src:/var/www/html
      - ./config/php-apache/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      TZ: Asia/Seoul
    networks:
      - apm-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  tunnel:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    depends_on:
      - web
    networks:
      - apm-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  apm-network:
    driver: bridge