services:
  db:
    image: mariadb:10.11
    container_name: apm-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - apm-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"