# .docker/php.ini
date.timezone = Asia/Seoul
upload_max_filesize = 64M
post_max_size = 64M

display_errors = On
error_reporting = E_ALL

[opcache]
opcache.enable=1
opcache.memory_consumption=256
opcache.max_accelerated_files=20000
opcache.revalidate_freq=0
opcache.validate_timestamps=1