[supervisord]
nodaemon=true ; 도커가 종료되지 않도록 포그라운드로 실행
pidfile=/tmp/supervisord.pid ; <--- 이 줄을 추가해 주세요!
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[include]
files = /etc/supervisor/conf.d/*.ini