[unix_http_server]
file=/tmp/supervisor.sock   ; 소켓 파일 경로

[supervisord]
nodaemon=true
user=root                   ; 실행 사용자
pidfile=/tmp/supervisord.pid
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

; 리모컨(supervisorctl)이 본체와 대화하기 위한 필수 인터페이스
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; 위에서 설정한 소켓 경로와 일치해야 함

[include]
files = /etc/supervisor/conf.d/*.ini